GET http://localhost:3000/api/get-posts

###

POST http://localhost:3000/api/create-post
content-type: application/json

{
    "text": "dudeish"
}

###
DELETE http://localhost:3000/api/delete-post?id=649923ea9d13dfee9b44c791

###

PUT http://localhost:3000/api/update-post?id=6493ddf6c087afa43c77093d
content-type: application/json

{
    "text": "dudeish"
}